const colors = require("tailwindcss/colors");
module.exports = {
  purge: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  darkMode: "class", // or 'media' or 'class'
  theme: {
    colors: {
      transparent: "transparent",
      current: "currentColor",
      primary: "#DB5461",
      primaryVariant: colors.white,
      secondary: "#E3F2FD",
      secondaryVariant: "#bfdbfe",
      tertiary: "#686963",
      quaternary: "#8AA29E",
      quinary: "#FAFAFA",
      dark: "#292929",
      darkPrimary: colors.white,
      darkPrimaryVariant: colors.black,
      darkSecondary: "#bfdbfe",
      darkSecondaryVariant: "#3b82f6",
      darkHeader: "#1f1f1f",
      success: "#22bb33",
      warning: "#ffc107",
      danger: "#dc3545",
      muted: "#6c757d",
      hover: "rgba(255, 255, 255, 0.1)",
      black: colors.black,
      white: colors.white,
      gray: colors.trueGray,
      indigo: colors.indigo,
      red: colors.rose,
      yellow: colors.amber,
    },
    zIndex: {
      neg50: -50,
      neg40: -40,
      neg30: -30,
      neg20: -20,
      neg10: -10,
      0: 0,
      10: 10,
      20: 20,
      30: 30,
      40: 40,
      50: 50,
      100: 100,
      auto: "auto",
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
